---
title: "Week7_Assignment"
author: "YoungKoung Kim"
date: "March 17, 2018"
output: html_document
---

### Required Libaray

```{r warning = FALSE}
library(XML)
library(knitr)
library(rjson)
library(httr)
```


### XML

#### XML file
Here is the XML file for my favorite books. 

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<books>
<book id = "1">
    <title>The Vegetarian</title>
    <author>Han Kang</author>
    <year>2007</year>
    <genre>Contemporary fiction</genre>
    <language>Korean</language>
    <page>160</page>
</book>
<book id = "2">
    <title>One Hundred Years of Solitude</title>
    <author>Gabriel Garcia Marquez </author>
    <year>1967</year>
    <genre>Magic realism</genre>
    <language>Spanish</language>
    <page>422</page>    
</book>
<book id = "3">
    <title>Norwegian Wood</title>
    <author>Haruki Murakami</author>
    <year>1987</year>
    <genre>Coming of age novel</genre>
    <language>Japanese</language>
    <page>296</page>    
</book>
</books>
```

#### Create R data frame from XML file

```{r}
xmlFile <- GET("https://raw.githubusercontent.com/ykkim08/CUNY-DATA607/master/books.xml")
books_xml <- xmlParse(xmlFile)
book_xml_root <- xmlRoot(books_xml)
bookXML.df <- xmlToDataFrame(book_xml_root)
kable(head(bookXML.df))
```

### HTML table

#### HTML table file
Here is the HTML table file for my favorite books. 

```
<TABLE border=1>
<Caption>Book</Caption>
<TR>
<TH>Title</TH>
<TH>Author</TH>
<TH>Year</TH>
<TH>Genre</TH>
<TH>Language</TH>
<TH>Page</TH>
</TR>
<TR Align=Center>
<TD>The Vegetarian</TD>
<TD>Han Kang</TD>
<TD>2007</TD>
<TD>Contemporary fiction</TD>
<TD>Korean</TD>
<TD>160</TD>
</TR>
<TR Align=Center>
<TD>One Hundred Years of Solitude</TD>
<TD>Gabriel Garcia Marquez</TD>
<TD>1967</TD>
<TD>Magic realism</TD>
<TD>Spanish</TD>
<TD>422</TD>
</TR>
<TR Align=Center>
<TD>Norwegian Wood</TD>
<TD>Haruki Murakami</TD>
<TD>1987</TD>
<TD>Coming of age novel</TD>
<TD>Japanese</TD>
<TD>296</TD>
</TR>
</TABLE>
```
#### Create R data frame from HTML table file

```{r}
htmlFile <- GET("https://raw.githubusercontent.com/ykkim08/CUNY-DATA607/master/books.html")
htmlFile <- content(htmlFile)
books_html <- readHTMLTable(htmlFile)
bookhtml.df <- books_html[[1]]
kable((bookhtml.df))
```


### JSON 

#### HTML table file
Here is the HTML table file for my favorite books. 

```
{
    "Title": ["The Vegetarian", "One Hundred Years of Solitude", "Norwegian Wood"],
    "Author": ["Han Kang", "Gabriel Garcia Marquez", "Haruki Murakami"],
    "Year" : ["2007", "1967", "1987"],
    "Genre": ["Contemporary fiction", "Maic realism", "Coming of age novel"],
    "Language": ["Korean", "Spanish", "Japanese"],
    "Page": ["160", "422", "296"]

}
```
#### Create R data frame from JSON file

```{r}
jsonFile <- GET("https://raw.githubusercontent.com/ykkim08/CUNY-DATA607/master/books.json")
jsonFile <- content(jsonFile)
books_json <- fromJSON(jsonFile)
bookjson.df <- as.data.frame(books_json)
kable(head(bookjson.df))
```

####Yes, The three data frames are identical!

